### ISSUE TITLE
Poll healthcare.gov QHP plans

### ISSUE THREAD

**Issue by jtmoulia** [DocDir/docdir#4]
Socrata [API Info](https://data.healthcare.gov/developers/docs/qhp-landscape-individual-market-medical)

Note that the plans are organized _per county_.

**Comment by clarktheshark** [comment]
also forgot to mention it seemed silly to require an instance of the class hence all the class methods, but if it makes more sense I can definitely them to instance-based methods

**Comment by jtmoulia** [comment]
> also forgot to mention it seemed silly to require an instance of the class hence all the class methods, but if it makes more sense I can definitely them to instance-based methods

Totally makes sense to not require instances where not necessary -- might they just be module level functions instead then? I suppose nice thing about the `@classmethod` approach is that it allows the methods to be overridden by subclasses. If that's the intention, then :+1: .

**Comment by clarktheshark** [comment]
> I suppose nice thing about the @classmethod approach is that it allows the methods to be overridden by subclasses. If that's the intention, then :+1: .

Yup, that was exactly it. Just so I don't have to keep reminding myself, this db only contains ~35 states worth of data, EXCLUDING California.

**Comment by jtmoulia** [comment]
Sweet, closing!
